### ISSUE TITLE
git fzf help

### ISSUE THREAD

**Issue by rpietro** [Synthetica9/git-fzf#1]
Hi, I tried:

> git fzf help

which I got from [here](https://github.com/Synthetica9/git-fzf/blob/master/git-fzf.sh) but got an error:

> f() { /home/user/git-fzf/git-fzf.sh $@ }; f: -c: line 1: syntax error: unexpected end of file

Also, I assumed that the command to trigger fzf would be 

> git fzf log

but it also gives me the same error. Any thoughts?

thanks for the repo, it does look cool.

**Comment by Synthetica9** [comment]
Is `git-fzf.sh` located at `/home/user/git-fzf/git-fzf.sh`? I can recreate this exact error when I delete the file on my machine.

**Comment by rpietro** [comment]
Sorry, my computer died and it took me a while to get back on my feet. Actually, the problem I was having was related to a hardware issue. Working perfectly now. Thanks again for the software.
